### ISSUE TITLE
[BUG?] Interaction with image toolkit stopped working

### ISSUE THREAD

**Issue by mretier** [vertis/obsidian-image-layouts#10]
Hi,
first, thanks for this great plugin.

I'm using Image Layouts together with another Obsidian plugin, [Image Toolkit](https://github.com/sissilab/obsidian-image-toolkit) to make images full screen.

The two plugins used to interact smoothly with each other until the most recent update, I believe. Now, I can't make images integrated with Image Layouts fullscreen anymore.

Any change interoperability will be restored sometime in the future again?

Thanks,
Michael

**Comment by vertis** [comment]
I'm not aware of Image Toolkit but there has been no planned interoperability with other plugins.

**Comment by vertis** [comment]
Solved by version 0.14.0. The overlays were interfering with the image click. This should now be solved.

**Comment by mretier** [comment]
Awesome, thanks for fixing this :)
