### ISSUE TITLE
Failed to load image layout: Buffer is not defined

### ISSUE THREAD

**Issue by ckt1031** [vertis/obsidian-image-layouts#13]
This happens on my Android Obsidian application, it fails to show image layout when toggling source mode, and once I close it and open the file, it fails due to "Buffer is not defined"

I believe there's a node.js and browser compatibility issue with your library and code that might use the Node.js Buffer function.

![Screenshot_2024-02-11-12-39-47-708-edit_md obsidian](https://github.com/vertis/obsidian-image-layouts/assets/65409152/1e7e0cc8-d821-4ed9-8489-12c7b335a553)

**Comment by vertis** [comment]
@ckt1031 thank you, I don't use it on Android personally, I mostly use it on desktop. It has recently gotten to be a more complicated stack though so I'll investigate

**Comment by ckt1031** [comment]
I appreciate your response! It seems like the issue with `gray-matter`. Rolling back to version `0.10.0` should help resolve it.

**Comment by vertis** [comment]
@ckt1031 yes thank you. I've pushed a version 0.15.4 that no longer relies on gray-matter for the layouts. The new carousel but I'll need to fix that by replacing the yaml stringifying.
