### ISSUE TITLE
Feature request: single image 

### ISSUE THREAD

**Issue by maxhant** [vertis/obsidian-image-layouts#18]
I like to you your caption style, and I want this to be consistent across all my images. I would be nice to be able to also display only a single image like 

\``` image-masonry-1
\---
caption: Images\#^fig-TCRv1_rie
permanentOverlay: false # the default is false
\---
\!\[](./images/1.jpg)
\!\[](./images/2.jpg)
\```

**Comment by vertis** [comment]
I have added this feature in `0.15.5` with `image-layout-single` allowing for a single image and the caption/description. Sorry it took so long
