### ISSUE TITLE
Please add an extra layout that functions as image-slider

### ISSUE THREAD

**Issue by amatya-aditya** [vertis/obsidian-image-layouts#5]
It basically needs to have navigation (next and prev button ). Please do consider.

**Comment by vertis** [comment]
I am in the process of adding this. It's a non-trivial amount of work though.

**Comment by vertis** [comment]
The new release 0.15.0 has tentative support

**Comment by amatya-aditya** [comment]
I tried making one by myself but this one is better. Thank you for this ❤️

**Comment by vertis** [comment]
You're welcome
