### ISSUE TITLE
Plugin cannot be installed within obsidian

### ISSUE THREAD

**Issue by LillieoftheMoon** [vertis/obsidian-image-layouts#7]
The plugin is listed in the obsidian plugin library, but attempting to open the plugin about page / summary results in the error message `Failed to load plugin manifest`.

![Screenshot 2024-01-29 3 12 49 PM](https://github.com/vertis/obsidian-image-layouts/assets/114845732/67086d8d-8207-4768-800c-bde72d27c321)

![image](https://github.com/vertis/obsidian-image-layouts/assets/114845732/ac7998ff-24af-465f-af59-a167523df508)

(I would like to test this plugin out to see if it works for me, so if an alternative instruction guide for manual installation can be provided I'd appreciate it; not worries if not though!)

**Comment by vertis** [comment]
@LillieoftheMoon it's likely a problem with the new version. Thanks for the report

**Comment by vertis** [comment]
@LillieoftheMoon thank you for your help, I've fixed the problem

**Comment by LillieoftheMoon** [comment]
No problem! Double checked on my end, issue is fixed as stated.
Thank you!!
