### ISSUE TITLE
[Bug] After the update, masonry can't handle odd number of images correctly.

### ISSUE THREAD

**Issue by wwjCMP** [vertis/obsidian-image-layouts#9]
After the update, masonry can't handle odd number of images correctly, causing them to be misaligned. There's no issue with even number of images or in reading mode.

**Comment by vertis** [comment]
Thank you, I'll look into it

**Comment by vertis** [comment]
![Screenshot 2024-01-31 at 12 28 34](https://github.com/vertis/obsidian-image-layouts/assets/19705/8faec9a6-5c52-4914-b708-5ae9fd380084)

I'm not seeing a problem with the alignment with odd numbers of images

**Comment by vertis** [comment]
![Screenshot 2024-01-31 at 12 32 36](https://github.com/vertis/obsidian-image-layouts/assets/19705/d135573d-e5ed-40c0-9582-150513618157)

**Comment by wwjCMP** [comment]
masonry-2
![Snipaste_2024-01-31_23-40-30](https://github.com/vertis/obsidian-image-layouts/assets/32979859/a17c801e-78f1-4ac9-9ee0-03be7f13a3a3)

masonry-3
![Snipaste_2024-01-31_23-41-13](https://github.com/vertis/obsidian-image-layouts/assets/32979859/abad0493-9809-4f2c-9af0-53391cd1fd17)

masonry-4
![Snipaste_2024-01-31_23-40-57](https://github.com/vertis/obsidian-image-layouts/assets/32979859/6f6552a0-c5df-4252-969b-1da1fcbebfb8)

**Comment by vertis** [comment]
I can't see anything that would cause it to be like that, can you please send me a list of other plugins you use and which theme (if any) you use, and also try temporarily disabling other plugins and see if that resolves the issue.

**Comment by wwjCMP** [comment]
I don't know what the reason is either. But after updating this plugin, the problem was solved.

**Comment by vertis** [comment]
okay
